### ISSUE TITLE
UG/DG updates for earlier versions.

### ISSUE THREAD

**Issue by YiJiee** [AY1920S1-CS2103T-T10-4/main#113]
UG/DG work in progress.

Tag this issue if you have made changes to the UG/DG.

**Comment by aidilfbk** [comment]
While editing the user guide for #138, I noticed a few things.

- User guide states that we have the following commands: `delete-schedule`, `deleteschedule` and `group` command. @AY1920S1-CS2103T-T10-4/developers Are we implementing this?<br><br>
- Based on their `CommandParser`s, `addgroup` and `editgroup` command supports both `-r REMARK` and `-d DESCRIPTION` but user guide inconsistently documents both prefixes. I believe this was because of a mixup with the early Tutorial 3 (see #41). I think we can stick to one but I'm not sure which. @Alvinnyk thoughts?<br><br>
- User guide states the `addperson`, `addevent` commands supports `-c NUS_MOD_LINK` but their `CommandParser`s doesn't seem to be parsing for it. @marqueurs404 Should we should remove it from the user guide or write code to implement it?<br><br>
- User guide has sections for `export-ics` and `import-ics` command. @marqueurs404 Should we remove it?<br><br>
- Slightly off-tangent but @YiJiee what happened to your UG update from #114?
